### ISSUE TITLE
Handle empty query params

### ISSUE THREAD

**Issue by Schwartz10** [glifio/explorer#10]
/message and /actor pages should handle situation when no query param is passed, this is how it looks now

![image](https://user-images.githubusercontent.com/12353734/153236264-86949b4c-1ae4-4c5a-adf6-5a9e054861d7.png)

**Comment by navFooh** [comment]
Using `validateAddressString` from `@glif/filecoin-address`

![image](https://user-images.githubusercontent.com/394452/154729162-fe35ccc6-927a-4cc9-88c2-58101ccdde14.png)

**Comment by navFooh** [comment]
Same for transaction:

![image](https://user-images.githubusercontent.com/394452/154731051-3d74fb0e-bd48-47bf-9d16-21af8f3595f6.png)
