### ISSUE TITLE
Add AppHeader to explorer home page, actor page, and message page 

### ISSUE THREAD

**Issue by Schwartz10** [glifio/explorer#7]
We should link to:

- wallet
- safe
- verifier

And these links should be dealt with via environment variables - see [this](https://github.com/glifio/homepage/blob/primary/next.config.js#L23-L32) as an example

**Comment by navFooh** [comment]
Question, where does the Home button (Glif icon) go? Does it always go to the App overview page or to the landing page of the Explorer app? I suppose it would make most sense to go to the app overview, so that the behavious is the same across apps. What is the URL of the app overview?

**Comment by navFooh** [comment]
Or is it also a possibility that the Glif icon is just an icon (no link) when no `homeHref` is passed?
Again might be confusing if it is a link in some cases but not in others.
